name: Build

on:
  push:
    branches: [ "master" ]

jobs:
  proton:
    name: mkljczk-proton-bleeding-edge
    runs-on: ubuntu-latest
    steps:
    - name: Prepare host
      run: sudo apt update && sudo apt-get install -y ccache fontforge-nox

    - name: Download cache
      uses: actions/cache@v3
      with:
        path: ~/.ccache
        key: ccache-proton-${{ github.run_id }}
        restore-keys: |
          ccache-proton

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: recursive

    - name: Patch
      run: |
        # strip binaries at compile time to save space in the runner
        patch -Np1 -i ./.github/patches/0001-strip-binaries-early.patch
        # apply proton-ge-custom patches
        ./patches/protonprep-valve-staging.sh || true
        mkdir ./build

    - name: Configure
      working-directory: ./build
      run: ../configure.sh --build-name=mkljczk-proton-bleeding-edge --enable-ccache --container-engine=docker

    - name: Make mkljczk-proton-bleeding-edge
      working-directory: ./build
      run: make -j3 redist

    - name: Upload artifact mkljczk-proton-bleeding-edge.tar.gz
      uses: actions/upload-artifact@v3
      with:
        name: mkljczk-proton-bleeding-edge.tar.gz
        path: ./build/mkljczk-proton-bleeding-edge.tar.gz

    - name: Upload artifact mkljczk-proton-bleeding-edge.sha512sum
      uses: actions/upload-artifact@v3
      with:
        name: mkljczk-proton-bleeding-edge.sha512sum
        path: ./build/mkljczk-proton-bleeding-edge.sha512sum
